### ISSUE TITLE
JavaScript 'require' 关键字和背景颜色太相近

### ISSUE THREAD

**Issue by fewwwww** [ayako02/vscode-sodagreen-night-theme#1]
![截屏2021-06-13 下午11 42 30](https://user-images.githubusercontent.com/41555918/121813945-0922ab00-cca1-11eb-8192-6f78464bb5b6.png)

超喜欢这个theme，感谢作者

**Comment by ayako02** [comment]
好的, 谢谢告知, 这里会安排时间修改 ^^

**Comment by fewwwww** [comment]
谢谢！: >
